version: '3'
services:
    proxy:
        container_name: proxy
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro

    app:
        container_name: app
        image: nginx:alpine
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web:/var/www/html"
            - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    
        ports:
            - "8000:80"    

        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb

        links:
            - mysqldb
    php:
        container_name: php
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./web:/var/www/html"

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            PMA_HOST: ${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
        links:
            - mysqldb

        ports:
            - "9191:80"  
    mysqldb:
        container_name: ${MYSQL_HOST}
        image: mysql:${MYSQL_VERSION}
        restart: always
        env_file:
            - ".env"
        environment:
            MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
